#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: ./nb/common.ipynb
from xs_lib.common import *
export_notebook = Export_notebook('reduce_emb', working_dir_tag='notebooks')